name: run-tests
run-name: ${{ github.actor }} is running tests for wizard-score-keeper
on: [push]
jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm i
      - run: npm run test